//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingList.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemOptions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemOptions()
        {
            this.Item_ItemOptions = new HashSet<Item_ItemOptions>();
        }
    
        public decimal ItemOptionID { get; set; }
        public decimal ListTypeID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Validation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_ItemOptions> Item_ItemOptions { get; set; }
        public virtual ListType ListType { get; set; }
    }
}
