//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingList.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KingListDB_Dev : DbContext
    {
        public KingListDB_Dev()
            : base("name=KingListDB_Dev")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Folder> Folder { get; set; }
        public virtual DbSet<Folder_User> Folder_User { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<Item_ItemOptions> Item_ItemOptions { get; set; }
        public virtual DbSet<ItemOptions> ItemOptions { get; set; }
        public virtual DbSet<List> List { get; set; }
        public virtual DbSet<List_ListOptions> List_ListOptions { get; set; }
        public virtual DbSet<List_User> List_User { get; set; }
        public virtual DbSet<ListOptions> ListOptions { get; set; }
        public virtual DbSet<ListType> ListType { get; set; }
        public virtual DbSet<Subscription> Subscription { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<User_Item> User_Item { get; set; }
        public virtual DbSet<User_UserOptions> User_UserOptions { get; set; }
        public virtual DbSet<UserOptions> UserOptions { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
    }
}
