//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingList.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class List_User
    {
        public decimal UserID { get; set; }
        public decimal ListID { get; set; }
        public decimal FolderID { get; set; }
        public bool IsOwner { get; set; }
        public bool CanWrite { get; set; }
        public bool CanCheck { get; set; }
        public bool CanShare { get; set; }
        public bool CanDelete { get; set; }
        public int Index { get; set; }
    
        public virtual Folder Folder { get; set; }
        public virtual List List { get; set; }
        public virtual User User { get; set; }
    }
}
