//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingList.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class List_ListOptions
    {
        public decimal ListID { get; set; }
        public decimal ListOptionID { get; set; }
        public string Value { get; set; }
    
        public virtual List List { get; set; }
        public virtual ListOptions ListOptions { get; set; }
    }
}
